### ISSUE TITLE
Better handle lossy connection during discovery

### ISSUE THREAD

**Issue by karlkar** [Danielhiversen/PyXiaomiGateway#92]
Hello.
First of all - great work!
However I have a huge issue with my connection to the Gateway -it is very common case that some packets are lost. It is not an issue during normal operation, but during discovery phase it is critical to retry communication - otherwise I have to restart my HomeAssistant to discover devices that had issues during connection. I've done it just to check if it solves my issue and here's what I've found out.

First of all - the code I've modified - in _discover_devices I've put the following code:

```
        for sid in sids:
            cmd = '{"cmd":"read","sid":"' + sid + '"}'
            ret = 0
            while ret < 10:
                ret += 1
                _LOGGER.error("KAROL: retry: %d", ret)
                resp = self._send_cmd(cmd, "read_ack") if int(self.proto[0:1]) == 1 else self._send_cmd(cmd, "read_rsp")
                if _validate_data(resp):
                    break
            if not _validate_data(resp):
                _LOGGER.error("Not a valid device. Check the mac adress and update the firmware.")
                continue

            model = resp["model"]

```

How did the logs look like? It sometimes took up to 9 retries to get the data of the device to be discovered:

> 2018-09-06 08:57:27 ERROR (SyncWorker_0) [xiaomi_gateway] KAROL: retry: 1
2018-09-06 08:57:27 DEBUG (SyncWorker_0) [xiaomi_gateway] _send_cmd >> b'{"cmd":"read","sid":"my_secret_sid"}'
2018-09-06 08:57:37 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2018-09-06 08:57:37 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2018-09-06 08:57:37 ERROR (SyncWorker_0) [xiaomi_gateway] KAROL: retry: 2
2018-09-06 08:57:37 DEBUG (SyncWorker_0) [xiaomi_gateway] _send_cmd >> b'{"cmd":"read","sid":"my_secret_sid"}'
2018-09-06 08:57:47 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2018-09-06 08:57:47 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2018-09-06 08:57:47 ERROR (SyncWorker_0) [xiaomi_gateway] KAROL: retry: 3
2018-09-06 08:57:47 DEBUG (SyncWorker_0) [xiaomi_gateway] _send_cmd >> b'{"cmd":"read","sid":"my_secret_sid"}'
2018-09-06 08:57:57 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2018-09-06 08:57:57 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2018-09-06 08:57:57 ERROR (SyncWorker_0) [xiaomi_gateway] KAROL: retry: 4
2018-09-06 08:57:57 DEBUG (SyncWorker_0) [xiaomi_gateway] _send_cmd >> b'{"cmd":"read","sid":"my_secret_sid"}'
2018-09-06 08:58:07 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2018-09-06 08:58:07 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2018-09-06 08:58:07 ERROR (SyncWorker_0) [xiaomi_gateway] KAROL: retry: 5
2018-09-06 08:58:07 DEBUG (SyncWorker_0) [xiaomi_gateway] _send_cmd >> b'{"cmd":"read","sid":"my_secret_sid"}'
2018-09-06 08:58:17 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2018-09-06 08:58:17 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2018-09-06 08:58:17 ERROR (SyncWorker_0) [xiaomi_gateway] KAROL: retry: 6
2018-09-06 08:58:17 DEBUG (SyncWorker_0) [xiaomi_gateway] _send_cmd >> b'{"cmd":"read","sid":"my_secret_sid"}'
2018-09-06 08:58:27 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2018-09-06 08:58:27 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2018-09-06 08:58:27 ERROR (SyncWorker_0) [xiaomi_gateway] KAROL: retry: 7
2018-09-06 08:58:27 DEBUG (SyncWorker_0) [xiaomi_gateway] _send_cmd >> b'{"cmd":"read","sid":"my_secret_sid"}'
2018-09-06 08:58:37 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2018-09-06 08:58:37 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2018-09-06 08:58:37 ERROR (SyncWorker_0) [xiaomi_gateway] KAROL: retry: 8
2018-09-06 08:58:37 DEBUG (SyncWorker_0) [xiaomi_gateway] _send_cmd >> b'{"cmd":"read","sid":"my_secret_sid"}'
2018-09-06 08:58:47 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2018-09-06 08:58:47 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2018-09-06 08:58:47 ERROR (SyncWorker_0) [xiaomi_gateway] KAROL: retry: 9
2018-09-06 08:58:47 DEBUG (SyncWorker_0) [xiaomi_gateway] _send_cmd >> b'{"cmd":"read","sid":"my_secret_sid"}'
2018-09-06 08:58:47 DEBUG (SyncWorker_0) [xiaomi_gateway] _send_cmd resp << {'cmd': 'read_ack', 'model': 'switch', 'sid': 'my_secret_sid', 'short_id': 26023, 'data': '{"voltage":3062}'}

However now I have no issues with the discovery process - all the devices are discovered correctly and I no longer have to restart the HomeAssistant to run the discovery again.

**Comment by andriej** [comment]
Anything was fixed with that?

**Comment by karlkar** [comment]
As far as I know - no. However I still have the code from the report in my version off HA. Works great - no issues any more.

**Comment by andriej** [comment]
Can you provide PR for that please? I ain't developer but have issues regarding gateways. They may have been from lost packets (lots of network traffic)

**Comment by karlkar** [comment]
I did, but it didn't get merged;)
https://github.com/Danielhiversen/PyXiaomiGateway/pull/93

**Comment by andriej** [comment]
@danielhiversen can you please provide any info why this PR didn't get merged?

**Comment by karlkar** [comment]
Hi again @Danielhiversen 
Could you please explain why my PR is not merged yet?
It solves problem that touches many people. It really does. Instead of using it and making people's life's easier you are "working on an ultimate solution". Ok, I get it, you want to have it done right. Meanwhile since half of a year we have to face the issue, while the fix is already there, waiting for merge.
Can't you just merge it and revert when "ultimate solution" is ready?

**Comment by syssi** [comment]
I've read the code multiple times and I understand your solution now: It's very useful! I haven't realized the issue in the past. Some zigbee devices aren't discovered sometimes because HA misses the response.

**Comment by andriej** [comment]
So there's a chance for PR to be merged then?

**Comment by karlkar** [comment]
It looks like yes ;)
